// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dadrhsvcizaiodouxzaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhZHJoc3ZjaXphaW9kb3V4emFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MzY5ODAsImV4cCI6MjA2NTExMjk4MH0.DAMUwqwM38UfzU1tXkOXF12HY-xUcesKxVlB8m0dJgA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);